### ISSUE TITLE
/bin/sh: eval: line 66: .monorepo.gitlab/last_green_commit.sh: not found

### ISSUE THREAD

**Issue by nk2580** [awesome-inc/hello.gitlab.monorepo#2]
getting this error when running the tool in alpine on gitlab CI. seems the script isnt there anymore... but it looks like it is when i debug

**Comment by mkoertgen** [comment]
Please check you did the submodule setup [How to use](https://github.com/awesome-inc/hello.gitlab.monorepo#how-to-use) section.

Other than that i assume the she-bang `/bin/bash` won't work on alpine, cf.:

-  https://github.com/awesome-inc/monorepo.gitlab/blob/master/last_green_commit.sh#L1

Try changing to `/bin/sh` which should work on virtually all distros including alpine.
I don't think we are using any bash-specifics here, only `readlink + pushd/popd` which should be fine on alpine.

Note that the same holds for the other shell scripts too, i.e.:

- https://github.com/awesome-inc/monorepo.gitlab/blob/master/build_if_changed.sh#L1
- https://github.com/awesome-inc/monorepo.gitlab/blob/master/changes.sh#L1

If that works well, leave a message or feel free to submit a PR.

**Comment by nk2580** [comment]
Thank you for the answer, turns out it’s an issue with gitlab and GOPATH not playing nice... ended up using a custom tool instead. GOPATH is the bane of my existence atm!

**Comment by mkoertgen** [comment]
@nk2580 Ah, i see. Would you mind pointing me to that issue with GOPATH?
